version: '3'
services:

  scrapyd:
    image: thecloudminders/scrapyd:latest
    ports:
      - "6800:6800"
    volumes:
      - scrapyd:/scrapyd

  scrapydweb:
    image: thecloudminders/scrapydweb:latest
    entrypoint: dumb-init wait-for-it.sh -t 60 scrapyd:6800 -- scrapydweb
    depends_on:
      - scrapyd
    links:
      - scrapyd
    ports:
      - "5000:5000"
    environment:
      - SCRAPYD_ADMIN
      - SCRAPYD_PASSWD
      - SCRAPYD_SERVERS
      - DATABASE_URL

volumes:
  scrapyd:

